blank_issues_enabled: false
contact_links:
  - name: Have a question?
    url: https://github.com/ardatan/graphql-tools/discussions/new
    about:
      Not sure about something? need help from the community? have a question to our team? please
      ask and answer questions here.
  - name: Any issue with `npm audit`
    url: https://overreacted.io/npm-audit-broken-by-design/
    about:
      Please do not create issues about `npm audit` and you can contact with us directly for more
      questions.
