name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install Dependencies using Yarn
        run: yarn

      - name: Build Packages
        run: yarn build

      - name: Typecheck
        run: yarn workspace website run build

      - name: Algolia push
        run: yarn workspace website run algolia-sync
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          SITE_URL: https://graphql-tools.com/
